version: '3'
services:
  boulder:
    image: patsys/boulder 
    environment:
    - DB_CLEAN_INIT="true"
    - FAKE_DNS=10.77.77.77
    - ENVIRONMENT=testing
    networks:
      bluenet:
        ipv4_address: 10.77.77.77
        aliases:
        - sa.boulder
        - ca.boulder
        - ra.boulder
        - va.boulder
        - publisher.boulder
        - ocsp-updater.boulder
        - admin-revoker.boulder
        - nonce.boulder
        - sa1.boulder
        - ca1.boulder
        - ra1.boulder
        - va1.boulder
        - publisher1.boulder
      rednet:
        ipv4_address: 10.88.88.88
        aliases:
        - sa2.boulder
        - ca2.boulder
        - ra2.boulder
        - va2.boulder
        - publisher2.boulder
        - nonce2.boulder
    # Use sd-test-srv as a backup to Docker's embedded DNS server
    # (https://docs.docker.com/config/containers/container-networking/#dns-services).
    # If there's a name Docker's DNS server doesn't know about, it will
    # forward the query to this IP (running sd-test-srv). We have
    # special logic there that will return multiple IP addresses for
    # service names.
    dns: 10.77.77.77
    ports:
    - 4000:4000 # ACME
    - 4001:4001 # ACMEv2
    - 4002:4002 # OCSP
    - 4003:4003 # OCSP
    - 4430:4430 # ACME via HTTPS
    - 4431:4431 # ACMEv2 via HTTPS
    - 8055:8055 # dns-test-srv updates
    depends_on:
    - bmysql
  bmysql:
    image: mariadb:10.5
    networks:
      bluenet:
        aliases:
        - boulder-mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    # Send slow queries to a table so we can check for them in the
    # integration tests. For now we ignore queries not using indexes,
    # because that seems to trigger based on the optimizer's choice to not
    # use an index for certain queries, particularly when tables are still
    # small.
    command: mysqld --bind-address=0.0.0.0 --slow-query-log --log-output=TABLE --log-queries-not-using-indexes=ON
    logging:
      driver: none
#  phpmyadmin:
#    image: phpmyadmin/phpmyadmin
#    environment:
#      PMA_HOST: boulder-mysql
#    depends_on:
#    - bmysql
#    ports:
#    - 8080:80
#    depends_on:
#    - bmysql
#    networks:
#      bluenet: {}
networks:
  bluenet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.77.77.0/24
  rednet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.88.88.0/24
